<a href="https://colab.research.google.com/github/oyinloluwa20/oyinloluwa20/blob/deep-learning-01/fundamentals_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [ ]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3255, 0.3945, 0.4946, 0.1608],
        [0.7537, 0.3713, 0.1944, 0.8483],
        [0.4951, 0.6458, 0.8319, 0.5790]])

In [ ]:
#Find out details about a tensor
print(some_tensor)
print(f'Datatype of tensor:{ some_tensor.dtype}')
print(f'Shape of tensor:{ some_tensor.shape}')
print(f'The Device the tensor is on:{ some_tensor.device}')

tensor([[0.3255, 0.3945, 0.4946, 0.1608],
        [0.7537, 0.3713, 0.1944, 0.8483],
        [0.4951, 0.6458, 0.8319, 0.5790]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
The Device the tensor is on:cpu


In [ ]:
#Manipulating Tensors (Tensor operations)
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor *10

tensor([10, 20, 30])

In [ ]:
tensor -10

In [ ]:
## matrix matiplication
%%time
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
#matrix multiplication by hand
1*1+2*2+3*3

14

In [2]:
tensor_A =torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B =torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
#torch.mm(tensor_A, tensor_B) 
# torch.mm is the equivalent of matmul, i.e matrix multiplication
# Also the multiplication of tensor of the same shape wont work, so you get the transpose of one the tensors

In [3]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]), torch.Size([3, 2]))

In [4]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [5]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

**Finding the min, max,sum of tensor (tensor aggregation)**

create a tensor

In [6]:
x =torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

find the min

In [7]:
torch.min(x),x.min()

(tensor(0), tensor(0))

find the max

In [8]:
torch.max(x), x.max()

(tensor(90), tensor(90))

find the mean

In [9]:
torch.mean(x)

RuntimeError: ignored

In [10]:
#The datatype when finding the mean should always be floating point or cmplex dtype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

Find the sum

In [11]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

**Finding the positional max and mix value with argmax and argmin**

In [12]:
torch.argmax(x)

tensor(9)

In [13]:
torch.argmin(x)

tensor(0)

In [14]:
# Using the positional max and min value as the matrix index
x[torch.argmax(x)], x[torch.argmin(x)]

(tensor(90), tensor(0))

**Reshaping, stacking, squeezing and unsqueezing**

* Reshaping - reshapes an input tensor to a defined shape
* view - return a view of an input tensor of certain shape but keep the same memory as the original tensor
*stacking -combine multiple tensors on top of each other(vstack) or side by side(hstack)
*squeeze -removes all '1' dimensions from a tensor
*unsqeeze - add a '1' dimension to a target tensor
*permute - return a view of the input with dimensions permutted(swapped) in a certain way

In [27]:
a = torch.arange(1.0,10.0)
a, a.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [28]:
#Add an extra dimension
a_reshaped = a.reshape(1,9)
a_reshaped,  a_reshaped.shape
#Note the reshape has to be compatible with the original size

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [29]:
#change the view
z=a.view(1,9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [30]:
#changing z changes a because z shares the memory as a(the original input)
z[:, 0] = 5
z,a

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [32]:
# stack tensors on top of each other
a_stacked = torch.stack([a,a,a,a], dim = 0)
a_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [34]:
a_stacked = torch.stack([a,a], dim = 1)
a_stacked

tensor([[5., 5.],
        [2., 2.],
        [3., 3.],
        [4., 4.],
        [5., 5.],
        [6., 6.],
        [7., 7.],
        [8., 8.],
        [9., 9.]])