<a href="https://colab.research.google.com/github/oyinloluwa20/oyinloluwa20/blob/deep-learning-01/fundamentals_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8729, 0.9422, 0.5829, 0.3558],
        [0.9394, 0.3496, 0.5028, 0.6807],
        [0.0830, 0.3280, 0.7025, 0.3841]])

In [ ]:
#Find out details about a tensor
print(some_tensor)
print(f'Datatype of tensor:{ some_tensor.dtype}')
print(f'Shape of tensor:{ some_tensor.shape}')
print(f'The Device the tensor is on:{ some_tensor.device}')

tensor([[0.8729, 0.9422, 0.5829, 0.3558],
        [0.9394, 0.3496, 0.5028, 0.6807],
        [0.0830, 0.3280, 0.7025, 0.3841]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
The Device the tensor is on:cpu


In [ ]:
#Manipulating Tensors (Tensor operations)
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor *10

tensor([10, 20, 30])

In [ ]:
tensor -10

tensor([-9, -8, -7])

In [ ]:
## matrix matiplication
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.1 ms, sys: 1.03 ms, total: 2.13 ms
Wall time: 5.15 ms


tensor(14)

In [ ]:
#matrix multiplication by hand
1*1+2*2+3*3

14

In [ ]:
tensor_A =torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B =torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
#torch.mm(tensor_A, tensor_B) 
# torch.mm is the equivalent of matmul, i.e matrix multiplication
# Also the multiplication of tensor of the same shape wont work, so you get the transpose of one the tensors

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]), torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [ ]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

**Finding the min, max,sum of tensor (tensor aggregation)**

create a tensor

In [ ]:
x =torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

find the min

In [ ]:
torch.min(x),x.min()

(tensor(0), tensor(0))

find the max

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

find the mean

In [ ]:
torch.mean(x)

RuntimeError: ignored

In [ ]:
#The datatype when finding the mean should always be floating point or cmplex dtype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

Find the sum

In [ ]:
torch.sum(x), x.sum()

**Finding the positional max and mix value with argmax and argmin**

In [ ]:
torch.argmax(x)

In [ ]:
torch.argmin(x)

In [ ]:
# Using the positional max and min value as the matrix index
x[torch.argmax(x)], x[torch.argmin(x)]

**Reshaping, stacking, squeezing and unsqueezing**

* Reshaping - reshapes an input tensor to a defined shape
* view - return a view of an input tensor of certain shape but keep the same memory as the original tensor
*stacking -combine multiple tensors on top of each other(vstack) or side by side(hstack)
*squeeze -removes all '1' dimensions from a tensor
*unsqeeze - add a '1' dimension to a target tensor
*permute - return a view of the input with dimensions permutted(swapped) in a certain way

In [ ]:
a = torch.arange(1.0,10.0)
a, a.shape

In [ ]:
#Add an extra dimension
a_reshaped = a.reshape(1,9)
a_reshaped,  a_reshaped.shape
#Note the reshape has to be compatible with the original size

In [ ]:
#change the view
z=a.view(1,9)
z, z.shape


In [ ]:
#changing z changes a because z shares the memory as a(the original input)
z[:, 0] = 5
z,a

In [ ]:
# stack tensors on top of each other
a_stacked = torch.stack([a,a,a,a], dim = 0)
a_stacked


In [ ]:
a_stacked = torch.stack([a,a], dim = 1)
a_stacked

In [ ]:
#removes all 1 dimension in a tensor
b = a_reshaped.squeeze()
b, b.shape

In [ ]:
#torch.unsqueeze() - adds an extra dimension to a target tensor at a specific dim
print(f"The squeezed tensor is {b} with a shape of {b.shape}")
# adding a 1 dimension to the zero index
b_unsqueeze =b.unsqueeze(dim =0)
print(f'The unsqueesed tensor {b_unsqueeze} has a shape of {b_unsqueeze.shape} ')

In [ ]:
#torch.permute - rearranges the dimension of a target tensor in a specificied order

x = torch.randn([3,5,8])
x.shape
x1= torch.permute(x,(2,0,1))
x1.shape

**Indexing (selecting data fom tensors)**

In [ ]:
# STEP 1 : Create a Tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
x[0]

In [ ]:
x[0,0]

In [ ]:
x[0,1,1]

In [ ]:
x[0,2,2]

In [ ]:
#you can use : to select all the dimension of a target tensor
x[:,0]

In [ ]:
# Get all the values of 0th and 1st dimension but only index one of the 1 dimension
x[:,: ,1]

**Pytorch tensors & Numpy** :
Numpy is a popular scientific python numerical computing library and because of this,Pytorch has functionality to interact with it.
* To convert data in Numpy to pyTorch tensor -> torch.from_numpy(ndarray)
* To convert pytorch tensor to numpy -> torch.Tensor.numpy()

In [ ]:
import torch
import numpy as np

In [ ]:
#The default datatype for numpy is float64, while the default datatype for pytorch is float 32
#To convert from float64 to float32, you use the '.type(torch.float32)'
#the torch.from_numpy takes no prameter
array =np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#Tensor to Numpy array
#when converting from either pytorch to numpy or numpy to pytorch it is import to know that the default datatype does not change
#The newly converted tensor does not share the same location in memory, so a change inthe value of an array after it has been converted does not lead to a change in data in the converted tensor and vice-versa
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducibility (trying to take the randomness out of random)

To reduce the randomness in neural networks and pytorch comes the concept of **random seed**

Essentially what the random seed is "flavour" the randomness



In [ ]:
#Let create a random but reproducable tensor
#The random seed can be any number and it should be set before everytime before the random number is generated

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A =torch.rand(3,4)

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_B =torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_B== random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##Running tensors and pytorch objects on the Gpu and making it faster


In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
!nvidia-smi

Sun Sep 25 14:56:00 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P8    11W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#Count number of devices
torch.cuda.device_count()

1