<a href="https://colab.research.google.com/github/oyinloluwa20/oyinloluwa20/blob/deep-learning-01/fundamentals_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3255, 0.3945, 0.4946, 0.1608],
        [0.7537, 0.3713, 0.1944, 0.8483],
        [0.4951, 0.6458, 0.8319, 0.5790]])

In [4]:
#Find out details about a tensor
print(some_tensor)
print(f'Datatype of tensor:{ some_tensor.dtype}')
print(f'Shape of tensor:{ some_tensor.shape}')
print(f'The Device the tensor is on:{ some_tensor.device}')

tensor([[0.3255, 0.3945, 0.4946, 0.1608],
        [0.7537, 0.3713, 0.1944, 0.8483],
        [0.4951, 0.6458, 0.8319, 0.5790]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
The Device the tensor is on:cpu


In [5]:
#Manipulating Tensors (Tensor operations)
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [6]:
tensor *10

tensor([10, 20, 30])

In [ ]:
tensor -10

In [7]:
## matrix matiplication
torch.matmul(tensor,tensor)

tensor(14)

In [8]:
#matrix multiplication by hand
1*1+2*2+3*3

14