<a href="https://colab.research.google.com/github/oyinloluwa20/oyinloluwa20/blob/deep-learning-01/fundamentals_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8654, 0.0491, 0.2346, 0.0226],
        [0.2491, 0.1469, 0.1760, 0.1718],
        [0.6031, 0.2690, 0.9398, 0.4696]])

In [3]:
#Find out details about a tensor
print(some_tensor)
print(f'Datatype of tensor:{ some_tensor.dtype}')
print(f'Shape of tensor:{ some_tensor.shape}')
print(f'The Device the tensor is on:{ some_tensor.device}')

tensor([[0.8654, 0.0491, 0.2346, 0.0226],
        [0.2491, 0.1469, 0.1760, 0.1718],
        [0.6031, 0.2690, 0.9398, 0.4696]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
The Device the tensor is on:cpu


In [4]:
#Manipulating Tensors (Tensor operations)
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [5]:
tensor *10

tensor([10, 20, 30])

In [6]:
tensor -10

tensor([-9, -8, -7])

In [7]:
## matrix matiplication
%%time
torch.matmul(tensor,tensor)

CPU times: user 2.72 ms, sys: 175 µs, total: 2.9 ms
Wall time: 7.7 ms


tensor(14)

In [8]:
#matrix multiplication by hand
1*1+2*2+3*3

14

In [9]:
tensor_A =torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B =torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
#torch.mm(tensor_A, tensor_B) 
# torch.mm is the equivalent of matmul, i.e matrix multiplication
# Also the multiplication of tensor of the same shape wont work, so you get the transpose of one the tensors

In [10]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]), torch.Size([3, 2]))

In [11]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [12]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

**Finding the min, max,sum of tensor (tensor aggregation)**

create a tensor

In [13]:
x =torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

find the min

In [14]:
torch.min(x),x.min()

(tensor(0), tensor(0))

find the max

In [15]:
torch.max(x), x.max()

(tensor(90), tensor(90))

find the mean

In [16]:
torch.mean(x)

RuntimeError: ignored

In [17]:
#The datatype when finding the mean should always be floating point or cmplex dtype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

Find the sum

In [18]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

**Finding the positional max and mix value with argmax and argmin**

In [ ]:
torch.argmax(x)

In [ ]:
torch.argmin(x)

In [ ]:
# Using the positional max and min value as the matrix index
x[torch.argmax(x)], x[torch.argmin(x)]

**Reshaping, stacking, squeezing and unsqueezing**

* Reshaping - reshapes an input tensor to a defined shape
* view - return a view of an input tensor of certain shape but keep the same memory as the original tensor
*stacking -combine multiple tensors on top of each other(vstack) or side by side(hstack)
*squeeze -removes all '1' dimensions from a tensor
*unsqeeze - add a '1' dimension to a target tensor
*permute - return a view of the input with dimensions permutted(swapped) in a certain way

In [19]:
a = torch.arange(1.0,10.0)
a, a.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [20]:
#Add an extra dimension
a_reshaped = a.reshape(1,9)
a_reshaped,  a_reshaped.shape
#Note the reshape has to be compatible with the original size

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [21]:
#change the view
z=a.view(1,9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [22]:
#changing z changes a because z shares the memory as a(the original input)
z[:, 0] = 5
z,a

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [23]:
# stack tensors on top of each other
a_stacked = torch.stack([a,a,a,a], dim = 0)
a_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [24]:
a_stacked = torch.stack([a,a], dim = 1)
a_stacked

tensor([[5., 5.],
        [2., 2.],
        [3., 3.],
        [4., 4.],
        [5., 5.],
        [6., 6.],
        [7., 7.],
        [8., 8.],
        [9., 9.]])

In [26]:
#removes all 1 dimension in a tensor
b = a_reshaped.squeeze()
b, b.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [28]:
#torch.unsqueeze() - adds an extra dimension to a target tensor at a specific dim
print(f"The squeezed tensor is {b} with a shape of {b.shape}")
# adding a 1 dimension to the zero index
b_unsqueeze =b.unsqueeze(dim =0)
print(f'The unsqueesed tensor {b_unsqueeze} has a shape of {b_unsqueeze.shape} ')

The squeezed tensor is tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) with a shape of torch.Size([9])
The unsqueesed tensor tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) has a shape of torch.Size([1, 9]) 


In [34]:
#torch.permute - rearranges the dimension of a target tensor in a specificied order

x = torch.randn([3,5,8])
x.shape
x1= torch.permute(x,(2,0,1))
x1.shape

torch.Size([8, 3, 5])

**Indexing (selecting data fom tensors)**

In [35]:
# STEP 1 : Create a Tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [36]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [37]:
x[0,0]

tensor([1, 2, 3])

In [38]:
x[0,1,1]

tensor(5)

In [39]:
x[0,2,2]

tensor(9)

In [40]:
#you can use : to select all the dimension of a target tensor
x[:,0]

tensor([[1, 2, 3]])

In [45]:
# Get all the values of 0th and 1st dimension but only index one of the 1 dimension
x[:,: ,1]

tensor([2, 5, 8])

**Pytorch tensors & Numpy** :
Numpy is a popular scientific python numerical computing library and because of this,Pytorch has functionality to interact with it.
* To convert data in Numpy to pyTorch tensor -> torch.from_numpy(ndarray)
* To convert pytorch tensor to numpy -> torch.Tensor.numpy()

In [46]:
import torch
import numpy as np

In [47]:
array =np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))